### ISSUE TITLE
Confirm templates

### ISSUE THREAD

**Issue by seanpoulter-foci** [PHACDataHub/sci-portal#12]
```[tasklist]
### Tasks
- [x] Follow up with Collin about RAD Lab modules
- [x] Ask Mike and Collin to confirm and prioritize modules
- [x] Confirm order (above)
```

**Comment by seanpoulter-foci** [comment]
From an email:

> Collin's templates (The tuberculosis templates (vertex-ai, cloud workstation), and the R-shiny one) come directly from his work with epidemiologists, so I'd like to prioritize those over the rad-lab and HPC modules.
