### ISSUE TITLE
Provision a GCP Project from Backstage

### ISSUE THREAD

**Issue by seanpoulter-foci** [PHACDataHub/sci-portal#7]
When I create a new GCP Project
Then it will create a folder inside *SciencePlatorm*
And it will create a project inside that folder

For example:

- **Folder Name**: e.g: ph-<name>
- **Project Name**: e.g.: phx-<name>  
  _Description of naming conventions_
- **Display Name**: x

For the steps:

- Folder/Project
- Admin details

--

The project naming convention is:
- PHX, eX
- phD, Dev
- phT, Test,
- phP, Prod

--

```[tasklist]
### Tasks
- [x] Create a template
- [x] A PR should create a Claim or Composite Resource
- [x] Our Backstage action will create a file in the right path. For example, DMIA-PHAC/Experimentation/ph-christopherjobson/uuid.yaml
- [x] Create the Crossplane Composite Resource Definition
- [ ] Add project ID using a ULID
```

We'll follow up on the ULID in #111.
