### ISSUE TITLE
Deploy Backstage in test environment

### ISSUE THREAD

**Issue by seanpoulter-foci** [PHACDataHub/sci-portal#76]
As a Developer in **org.yaml** I should be able to connect to Backstage by port forwarding and create a PR in the repo.

```[tasklist]
### Tasks
- [ ] https://github.com/PHACDataHub/sci-portal/issues/77
- [ ] https://github.com/PHACDataHub/sci-portal/issues/79
- [ ] https://github.com/PHACDataHub/sci-portal/issues/80
- [x] Configure the script to run in the test environment
- [x] Push the latest code to PHACDataHub
- [x] Schedule meeting with the team to run the script(s)
- [x] Enable Private Marketplace service(s)
- [x] Create the cluster secret for the GitHub App *credentials.yaml file
- [x] The PHAC dev team run the bootstrap scripts
- [x] Troubleshoot access to Backstage
```
