### ISSUE TITLE
Configure Cost Dashboard to allow iFrame for Looker Studio

### ISSUE THREAD

**Issue by KDezenosky** [PHACDataHub/sci-portal#84]
```[tasklist]
### Tasks
- [x] Investigate opensource iFrame plugin vs. TechDocs plugin with iFrames
- [x] Add in selected plugin
- [x] Create iFrame from looker studio
```

**Comment by seanpoulter-foci** [comment]
The next step is to review with Mike and Seb.
